services:
  smedanno:
    build: .
    image: smedanno
    env_file:
      - .env
    working_dir: /smedanno
    volumes:
      # Mounts the script's directory
      - .:/smedanno
      # Mounts the data and output directories using variables from the .env file
      - ${DATA_PATH}:/data
      - ${OUTPUT_PATH}:/output
