# This file is now simplified, as the wrapper script handles dynamic volume mounts.
services:
  smedanno:
    build: .
    image: smedanno
    user: root
    env_file:
      - .env
    working_dir: /smedanno
    volumes:
      # Mounts the script's directory and the output directory.
      # All other input directories are now mounted dynamically by run_smedanno.sh
      - .:/smedanno
      - ${OUTPUT_PATH}:/output
      
